server:
#       _____   ______   ______   _____   _   _   ______   _  __        ____    _         ____     _____   _  __  _        _____    _____   _______
#      / ____| |  ____| |  ____| |_   _| | \ | | |  ____| | |/ /       |  _ \  | |       / __ \   / ____| | |/ / | |      |_   _|  / ____| |__   __|
#     | (___   | |__    | |__      | |   |  \| | | |__    | ' /        | |_) | | |      | |  | | | |      | ' /  | |        | |   | (___      | |
#      \___ \  |  __|   |  __|     | |   | . ` | |  __|   |  <         |  _ <  | |      | |  | | | |      |  <   | |        | |    \___ \     | |
#      ____) | | |____  | |       _| |_  | |\  | | |____  | . \        | |_) | | |____  | |__| | | |____  | . \  | |____   _| |_   ____) |    | |
#     |_____/  |______| |_|      |_____| |_| \_| |______| |_|\_\       |____/  |______|  \____/   \_____| |_|\_\ |______| |_____| |_____/     |_|
#
#                                            The best blocklist collection: https://blocklist.sefinek.net
# Title: AdGuard Apps Blocklist
# Description: N/A
# Expires: 1 day
# Count: 18 domains
# Source: https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardApps.txt
# License: MIT
# Release: Unbound
# Last update: April 15, 2026 at 7:17 PM UTC | 2026-04-15T19:17:12.872Z
#
# This file is part of the Sefinek Blocklist Collection, maintained by Sefinek.
# If you encounter any false positives, please report them at: https://blocklist.sefinek.net/false-positives
# -------------------------------------------------------------------------------------------------------------------------------------------------------
local-zone: "ads.viber.com." always_nxdomain
local-zone: "ads-d.viber.com." always_nxdomain
local-zone: "ads.aws.viber.com." always_nxdomain
local-zone: "adcs.rqmob.com." always_nxdomain
local-zone: "preitem.wshareit.com." always_nxdomain
local-zone: "mobimagic.com." always_nxdomain
local-zone: "adywind.com." always_nxdomain
local-zone: "hasmobi.net." always_nxdomain
local-zone: "api-a.op-mobile.opera.com." always_nxdomain
local-zone: "promotion.polarisoffice.com." always_nxdomain
local-zone: "newad.ifeng.com." always_nxdomain
local-zone: "afreeca-tag.ad-mapps.com." always_nxdomain
local-zone: "mtag.mman.kr." always_nxdomain
local-zone: "etl.tindersparks.com." always_nxdomain
local-zone: "d27tpsznug51gz.cloudfront.net." always_nxdomain
local-zone: "sensors.larkplayerapp.com." always_nxdomain
local-zone: "sensors.snaptubeapp.com." always_nxdomain
local-zone: "log.kajicam.com." always_nxdomain