server:
#       _____   ______   ______   _____   _   _   ______   _  __        ____    _         ____     _____   _  __  _        _____    _____   _______
#      / ____| |  ____| |  ____| |_   _| | \ | | |  ____| | |/ /       |  _ \  | |       / __ \   / ____| | |/ / | |      |_   _|  / ____| |__   __|
#     | (___   | |__    | |__      | |   |  \| | | |__    | ' /        | |_) | | |      | |  | | | |      | ' /  | |        | |   | (___      | |
#      \___ \  |  __|   |  __|     | |   | . ` | |  __|   |  <         |  _ <  | |      | |  | | | |      |  <   | |        | |    \___ \     | |
#      ____) | | |____  | |       _| |_  | |\  | | |____  | . \        | |_) | | |____  | |__| | | |____  | . \  | |____   _| |_   ____) |    | |
#     |_____/  |______| |_|      |_____| |_| \_| |______| |_|\_\       |____/  |______|  \____/   \_____| |_|\_\ |______| |_____| |_____/     |_|
#
# Title: Block all X (Twitter) domains
# Description: Blocks all X (formerly Twitter) related domains, preventing access via your DNS server to the platform.
# Entries: 27 domains
# Author: Sefinek <contact@sefinek.net> (https://sefinek.net)
# License: CC BY-NC-ND 4.0
# Format: Unbound
# Expires: 1 day
# Last updated: April 18, 2026 at 10:37 PM UTC | 2026-04-18T22:37:42.007Z
#
# This file is part of the Sefinek Blocklist Collection, maintained by Sefinek.
# Homepage: https://blocklist.sefinek.net
# Report false positives: https://blocklist.sefinek.net/false-positives
# -------------------------------------------------------------------------------------------------------------------------------------------------------
local-zone: "abs-0.twimg.com." always_nxdomain
local-zone: "abs.twimg.com." always_nxdomain
local-zone: "api.twitter.com." always_nxdomain
local-zone: "blog.twitter.co." always_nxdomain
local-zone: "cdn.cms-twdigitalassets.com." always_nxdomain
local-zone: "developers.twitter.com." always_nxdomain
local-zone: "fonts.twitter.com." always_nxdomain
local-zone: "help.twitter.com." always_nxdomain
local-zone: "mobile.twitter.co." always_nxdomain
local-zone: "mobile.twitter.co.uk." always_nxdomain
local-zone: "mobile.twitter.com." always_nxdomain
local-zone: "mobile.twitter.com.au." always_nxdomain
local-zone: "pbs.twimg.com." always_nxdomain
local-zone: "platform.twitter.com." always_nxdomain
local-zone: "syndication.twitter.com." always_nxdomain
local-zone: "twitter.co." always_nxdomain
local-zone: "twitter.co.uk." always_nxdomain
local-zone: "twitter.com." always_nxdomain
local-zone: "twitter.com.au." always_nxdomain
local-zone: "twitterinc.tt.omtrdc.net." always_nxdomain
local-zone: "video.twimg.com." always_nxdomain
local-zone: "www.twitter.co." always_nxdomain
local-zone: "www.twitter.co.uk." always_nxdomain
local-zone: "www.twitter.com." always_nxdomain
local-zone: "www.twitter.com.au." always_nxdomain
local-zone: "x.com." always_nxdomain
local-zone: "www.com." always_nxdomain
