server:
#       _____   ______   ______   _____   _   _   ______   _  __        ____    _         ____     _____   _  __  _        _____    _____   _______
#      / ____| |  ____| |  ____| |_   _| | \ | | |  ____| | |/ /       |  _ \  | |       / __ \   / ____| | |/ / | |      |_   _|  / ____| |__   __|
#     | (___   | |__    | |__      | |   |  \| | | |__    | ' /        | |_) | | |      | |  | | | |      | ' /  | |        | |   | (___      | |
#      \___ \  |  __|   |  __|     | |   | . ` | |  __|   |  <         |  _ <  | |      | |  | | | |      |  <   | |        | |    \___ \     | |
#      ____) | | |____  | |       _| |_  | |\  | | |____  | . \        | |_) | | |____  | |__| | | |____  | . \  | |____   _| |_   ____) |    | |
#     |_____/  |______| |_|      |_____| |_| \_| |______| |_|\_\       |____/  |______|  \____/   \_____| |_|\_\ |______| |_____| |_____/     |_|
#
# Tytuł: Block all Valve game domains
# Opis: Blocks all Valve game domains, including Steam, CS2, Dota 2, and other Valve titles and services.
# Entries: 12 domains
# Autor: Sefinek <contact@sefinek.net> (https://sefinek.net)
# Licencja: CC BY-NC-ND 4.0
# Format: Unbound
# Wygasa: 1 dzień
# Ostatnia aktualizacja: April 18, 2026 at 10:21 PM UTC | 2026-04-18T22:21:52.330Z
#
# Ten plik jest częścią Sefinek Blocklist Collection, utrzymywanej przez Sefinek.
# Oficjalna strona: https://blocklist.sefinek.net
# Zgłoś fałszywe pozytywy: https://blocklist.sefinek.net/false-positives
# -------------------------------------------------------------------------------------------------------------------------------------------------------
local-zone: "counter-strike.net." always_nxdomain
local-zone: "csgo.com." always_nxdomain
local-zone: "dayofdefeat.com." always_nxdomain
local-zone: "dota2.com." always_nxdomain
local-zone: "half-life.com." always_nxdomain
local-zone: "hl2.net." always_nxdomain
local-zone: "left4dead.com." always_nxdomain
local-zone: "portal2.com." always_nxdomain
local-zone: "ricochet.com." always_nxdomain
local-zone: "teamfortress.com." always_nxdomain
local-zone: "tf2.com." always_nxdomain
local-zone: "tf2maps.net." always_nxdomain
