server:
#       _____   ______   ______   _____   _   _   ______   _  __        ____    _         ____     _____   _  __  _        _____    _____   _______
#      / ____| |  ____| |  ____| |_   _| | \ | | |  ____| | |/ /       |  _ \  | |       / __ \   / ____| | |/ / | |      |_   _|  / ____| |__   __|
#     | (___   | |__    | |__      | |   |  \| | | |__    | ' /        | |_) | | |      | |  | | | |      | ' /  | |        | |   | (___      | |
#      \___ \  |  __|   |  __|     | |   | . ` | |  __|   |  <         |  _ <  | |      | |  | | | |      |  <   | |        | |    \___ \     | |
#      ____) | | |____  | |       _| |_  | |\  | | |____  | . \        | |_) | | |____  | |__| | | |____  | . \  | |____   _| |_   ____) |    | |
#     |_____/  |______| |_|      |_____| |_| \_| |______| |_|\_\       |____/  |______|  \____/   \_____| |_|\_\ |______| |_____| |_____/     |_|
#
#                                            The best blocklist collection: https://blocklist.sefinek.net
# Title: Block websites reported by Norton Antivirus as malicious
# Description: These websites may contain malware, viruses, phishing scams, or other types of harmful content. Remember not to visit these websites.
# Expires: 1 day
# Count: 16 domains
# Author: Sefinek (https://sefinek.net) <contact@sefinek.net>
# License: CC BY-NC-ND 4.0
# Release: Unbound
# Last update: April 15, 2026 at 7:17 PM UTC | 2026-04-15T19:17:12.778Z
#
# This file is part of the Sefinek Blocklist Collection, maintained by Sefinek.
# If you encounter any false positives, please report them at: https://blocklist.sefinek.net/false-positives
# -------------------------------------------------------------------------------------------------------------------------------------------------------
local-zone: "ccmwigksgiwwke.xyz." always_nxdomain
local-zone: "cnkapolr.xyz." always_nxdomain
local-zone: "jpfwbamawhkus.xyz." always_nxdomain
local-zone: "jtqejhfy.xyz." always_nxdomain
local-zone: "khdguudttddxe.xyz." always_nxdomain
local-zone: "lugjdylyqc.xyz." always_nxdomain
local-zone: "rwgyxqmfbhamol.xyz." always_nxdomain
local-zone: "tnfranfxmg.xyz." always_nxdomain
local-zone: "www.ccmwigksgiwwke.xyz." always_nxdomain
local-zone: "www.cnkapolr.xyz." always_nxdomain
local-zone: "www.jpfwbamawhkus.xyz." always_nxdomain
local-zone: "www.jtqejhfy.xyz." always_nxdomain
local-zone: "www.khdguudttddxe.xyz." always_nxdomain
local-zone: "www.lugjdylyqc.xyz." always_nxdomain
local-zone: "www.rwgyxqmfbhamol.xyz." always_nxdomain
local-zone: "www.tnfranfxmg.xyz." always_nxdomain