server:
#       _____   ______   ______   _____   _   _   ______   _  __        ____    _         ____     _____   _  __  _        _____    _____   _______
#      / ____| |  ____| |  ____| |_   _| | \ | | |  ____| | |/ /       |  _ \  | |       / __ \   / ____| | |/ / | |      |_   _|  / ____| |__   __|
#     | (___   | |__    | |__      | |   |  \| | | |__    | ' /        | |_) | | |      | |  | | | |      | ' /  | |        | |   | (___      | |
#      \___ \  |  __|   |  __|     | |   | . ` | |  __|   |  <         |  _ <  | |      | |  | | | |      |  <   | |        | |    \___ \     | |
#      ____) | | |____  | |       _| |_  | |\  | | |____  | . \        | |_) | | |____  | |__| | | |____  | . \  | |____   _| |_   ____) |    | |
#     |_____/  |______| |_|      |_____| |_| \_| |______| |_|\_\       |____/  |______|  \____/   \_____| |_|\_\ |______| |_____| |_____/     |_|
#
#                                            The best blocklist collection: https://blocklist.sefinek.net
# Title: Blocks anime websites
# Description: N/A
# Expires: 1 day
# Count: <Count>
# Author: Sefinek (https://sefinek.net) <contact@sefinek.net>
# Modified by: N/A
# Source: N/A
# License: CC BY-NC-ND 4.0
# Release: Unbound
# Last update: April 8, 2026 at 7:52 PM UTC | 2026-04-08T19:52:46.821Z
#
# This file is part of the Sefinek Blocklist Collection, maintained by Sefinek.
# If you encounter any false positives, please report them at: https://blocklist.sefinek.net/false-positives
# -------------------------------------------------------------------------------------------------------------------------------------------------------
local-zone: "9anime.to." always_nxdomain
local-zone: "animefreak.tv." always_nxdomain
local-zone: "animeheaven.ru." always_nxdomain
local-zone: "animepahe.com." always_nxdomain
local-zone: "animesuge.to." always_nxdomain
local-zone: "animixplay.to." always_nxdomain
local-zone: "api.nekosia.cat." always_nxdomain
local-zone: "bilibili.tv." always_nxdomain
local-zone: "cdn.myanimelist.net." always_nxdomain
local-zone: "cdn.nekosia.cat." always_nxdomain
local-zone: "chia-anime.su." always_nxdomain
local-zone: "crunchyroll.com." always_nxdomain
local-zone: "docs.nekos.best." always_nxdomain
local-zone: "fal.myanimelist.net." always_nxdomain
local-zone: "forum.shinden.pl." always_nxdomain
local-zone: "funimation.com." always_nxdomain
local-zone: "gogoanime3.co." always_nxdomain
local-zone: "hidive.com." always_nxdomain
local-zone: "kickassanime.am." always_nxdomain
local-zone: "masterani.me." always_nxdomain
local-zone: "mxj.myanimelist.net." always_nxdomain
local-zone: "myanimelist.net." always_nxdomain
local-zone: "nekoapi.com." always_nxdomain
local-zone: "nekos.best." always_nxdomain
local-zone: "nekosapi.com." always_nxdomain
local-zone: "nekosia.cat." always_nxdomain
local-zone: "shinden.pl." always_nxdomain
local-zone: "v1.nekosapi.com." always_nxdomain
local-zone: "www.9anime.to." always_nxdomain
local-zone: "www.animefreak.tv." always_nxdomain
local-zone: "www.animeheaven.ru." always_nxdomain
local-zone: "www.animepahe.com." always_nxdomain
local-zone: "www.animesuge.to." always_nxdomain
local-zone: "www.animixplay.to." always_nxdomain
local-zone: "www.bilibili.tv." always_nxdomain
local-zone: "www.chia-anime.su." always_nxdomain
local-zone: "www.crunchyroll.com." always_nxdomain
local-zone: "www.funimation.com." always_nxdomain
local-zone: "www.gogoanime3.co." always_nxdomain
local-zone: "www.hidive.com." always_nxdomain
local-zone: "www.kickassanime.am." always_nxdomain
local-zone: "www.masterani.me." always_nxdomain
local-zone: "www.myanimelist.net." always_nxdomain
local-zone: "www.shinden.pl." always_nxdomain
local-zone: "www.zoro.to." always_nxdomain
local-zone: "zoro.to." always_nxdomain